# Generated by Django 6.0.1 on 2026-03-14 12:19

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='gmailaccount',
            name='token_json',
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clientpdf',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='clientpdf',
            name='vector_id',
            field=models.CharField(blank=True, help_text='ID in vector store (Pinecone/Chroma/etc)', max_length=100),
        ),
        migrations.AddField(
            model_name='gmailaccount',
            name='access_token',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailaccount',
            name='authorization_error',
            field=models.TextField(blank=True, help_text='Last authorization error message'),
        ),
        migrations.AddField(
            model_name='gmailaccount',
            name='expiry',
            field=models.DateTimeField(blank=True, help_text='When access token expires', null=True),
        ),
        migrations.AddField(
            model_name='gmailaccount',
            name='last_processed_message_id',
            field=models.CharField(blank=True, help_text='Gmail message ID of last processed email', max_length=100),
        ),
        migrations.AddField(
            model_name='gmailaccount',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Last successful email sync', null=True),
        ),
        migrations.AddField(
            model_name='gmailaccount',
            name='refresh_token',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='details',
            field=models.TextField(blank=True, help_text='AI reply text, forward reason, or error'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bot_active',
            field=models.BooleanField(default=False, help_text='Bot is allowed to process emails'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin has approved this client'),
        ),
        migrations.AlterField(
            model_name='clientpdf',
            name='file',
            field=models.FileField(upload_to='client_pdfs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='gmailaccount',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_account', to='automation.client'),
        ),
        migrations.AlterField(
            model_name='gmailaccount',
            name='connected_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gmailaccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Gmail address'),
        ),
        migrations.AlterField(
            model_name='gmailaccount',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='OAuth tokens are valid'),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='action',
            field=models.CharField(choices=[('replied', 'Replied with AI'), ('forwarded', 'Forwarded to human'), ('ignored', 'Ignored / no action'), ('error', 'Processing failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_emails', to='automation.client'),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='gmail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_emails', to='automation.gmailaccount'),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='subject',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='processedemail',
            index=models.Index(fields=['message_id'], name='automation__message_c0ad1d_idx'),
        ),
        migrations.AddIndex(
            model_name='processedemail',
            index=models.Index(fields=['processed_at'], name='automation__process_3679c8_idx'),
        ),
    ]
