# Generated by Django 6.0.1 on 2026-03-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_alter_client_options_remove_gmailaccount_token_json_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='processedemail',
            name='automation__message_c0ad1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='processedemail',
            name='automation__process_3679c8_idx',
        ),
        migrations.RemoveField(
            model_name='clientpdf',
            name='processing_status',
        ),
        migrations.RemoveField(
            model_name='clientpdf',
            name='vector_id',
        ),
        migrations.RemoveField(
            model_name='gmailaccount',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='gmailaccount',
            name='authorization_error',
        ),
        migrations.RemoveField(
            model_name='gmailaccount',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='gmailaccount',
            name='last_processed_message_id',
        ),
        migrations.RemoveField(
            model_name='gmailaccount',
            name='last_sync_at',
        ),
        migrations.RemoveField(
            model_name='gmailaccount',
            name='refresh_token',
        ),
        migrations.AddField(
            model_name='gmailaccount',
            name='token_json',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='bot_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientpdf',
            name='file',
            field=models.FileField(upload_to='client_pdfs/'),
        ),
        migrations.AlterField(
            model_name='gmailaccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='gmailaccount',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='action',
            field=models.CharField(choices=[('replied', 'Replied'), ('forwarded', 'Forwarded'), ('ignored', 'Ignored'), ('error', 'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
